# Generated by Django 5.1.5 on 2025-01-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID ячейки')),
                ('size', models.CharField(choices=[('small', 'Маленькая (до 1 м³)'), ('medium', 'Средняя (1-5 м³)'), ('large', 'Большая (более 5 м³)')], max_length=10, verbose_name='Размер ячейки')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Занятость')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id пользователя')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID склада')),
                ('name', models.CharField(max_length=255, verbose_name='Название склада')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Текст напоминания')),
                ('reminder_date', models.DateTimeField(verbose_name='Дата отправки напоминания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_duration', models.PositiveIntegerField(verbose_name='Срок хранения (дни)')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Просрочен')], default='active', max_length=15, verbose_name='Статус заказа')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.storageunit', verbose_name='Ячейка хранения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='storageunit',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.warehouse', verbose_name='Склад'),
        ),
    ]
