# Generated by Django 5.1.5 on 2025-01-22 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО заказчика')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер тел.')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Тарифы хранения', 'Тарифы хранения'), ('Забор курьером', 'Забор курьером'), ('Самому привезти', 'Самому привезти'), ('Мои заказы', 'Мои заказы')], max_length=50, verbose_name='Тип заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('storage_duration', models.DurationField(blank=True, null=True, verbose_name='Срок хранения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
                ('order_type', models.ManyToManyField(to='reservations.ordertype', verbose_name='Тип заказа')),
            ],
        ),
    ]
