# Generated by Django 5.1.5 on 2025-01-23 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('expired', 'Просрочен'), ('completed', 'Закончен')], default='active', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
