# Generated by Django 5.1.5 on 2025-01-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_order_storage_duration_client_order_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
