# Generated by Django 5.1.5 on 2025-01-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageunit',
            name='is_occupied',
        ),
    ]
