# Generated by Django 5.1.5 on 2025-01-22 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_client_order_types_client_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа'),
        ),
    ]
