# Generated by Django 5.1.5 on 2025-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_storageunit_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Активен', 'Активен'), ('Просрочен', 'Просрочен'), ('Закончен', 'Закончен')], default='Активен', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
