# Generated by Django 5.1.5 on 2025-01-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('expired', 'Просрочен'), ('completed', 'Закончен')], default='active', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
