# Generated by Django 5.1.5 on 2025-01-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
