# Generated by Django 5.1.5 on 2025-01-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_order_total_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageunit',
            options={'verbose_name': 'Склад и ячейки'},
        ),
    ]
