# Generated by Django 5.1.5 on 2025-01-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_storageunit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='storageunit',
            options={'verbose_name': 'Кладовки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склады'},
        ),
    ]
