# Generated by Django 5.1.5 on 2025-01-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_order_options_alter_storageunit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageunit',
            options={'verbose_name': 'Боксы хранения'},
        ),
    ]
