# Generated by Django 5.1.5 on 2025-01-23 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_storageunit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='storageunit',
            options={'verbose_name_plural': 'Боксы хранения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Текст напоминания')),
                ('reminder_date', models.DateTimeField(verbose_name='Дата отправки напоминания')),
                ('storage_period', models.IntegerField(default=30, verbose_name='Срок хранения (дней)')),
                ('deletion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.user', verbose_name='Пользователь')),
            ],
        ),
    ]
