# Generated by Django 5.1.5 on 2025-01-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_order_options_alter_storageunit_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
