# Generated by Django 5.1.5 on 2025-01-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_delete_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес клиента'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес склада'),
        ),
    ]
