# Generated by Django 5.1.5 on 2025-01-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_user_user_address_warehouse_warehouse_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehouse_adress',
            new_name='warehouse_address',
        ),
    ]
