# Generated by Django 5.1.5 on 2025-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_rename_warehouse_adress_warehouse_warehouse_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала аренды'),
        ),
    ]
