# Generated by Django 5.1.5 on 2025-01-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_order_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активен'), ('expired', 'Просрочен'), ('completed', 'Закончен')], default='active', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
