# Generated by Django 5.1.5 on 2025-01-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name_plural': 'Реклама'},
        ),
    ]
