# Generated by Django 5.1.5 on 2025-01-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20250124_0135'),
        ('reservations', '0021_alter_advertisement_options'),
    ]

    operations = [
    ]
