# Generated by Django 5.1.5 on 2025-01-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_merge_20250124_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(unique=True, verbose_name='Оригинальная ссылка')),
                ('short_url', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Сокращенная ссылка')),
                ('click_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во кликов')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='storageunit',
            options={'verbose_name': 'Бокс хранения', 'verbose_name_plural': 'Боксы хранения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активен'), ('expired', 'Просрочен'), ('completed', 'Закончен')], db_index=True, default='active', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
