# Generated by Django 5.1.5 on 2025-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_link_delete_advertisement_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, verbose_name='Сокращенная ссылка'),
        ),
    ]
